### ISSUE TITLE
Update drawing detection

### ISSUE THREAD

**Issue by GautierR** [emiledecosterd/BoilingOnTubeBundles#10]
Possible improvement in 'mainWindow.py'

- Get rid of all the 'on_value_changed' function , simply call a new function who will use 'updateConfiguration' and then 'updateDrawing'. (Avoid to create one function by variable) This function could also be called by the resize window function.

- Create a dictionnary/list of the inputs widget (at least geom inputs) in order to create in a loop the signal required for the previous step

- The 'layout_lineEdit' if not part of the geom inputs dictionnary (only if corrPD is 'Gaddis')

**Comment by emiledecosterd** [comment]
Code refactoring done.
