### ISSUE TITLE
threading

### ISSUE THREAD

**Issue by emiledecosterd** [emiledecosterd/BoilingOnTubeBundles#3]
Threading does not work:

- Cannot stop simulation -> crashes
- Cannot start another simulation when the first is finished

**Comment by nielspichler** [comment]
Please Emile we are counting on you, it would be nice not to forget and disappoint us. Thanks in advance.

**Comment by vincentmayoraz** [comment]
Pleeeeaaaaaaaaaaaaaase

La teub
